=== Grom33/PMN-ERP/xml/payment/payments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="pmncloud"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="pmncloud"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Payments">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Payment">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element type="xs:int" name="Id"/>
                            <xs:element type="xs:date" name="Date"/>
                            <xs:element type="xs:decimal" name="Sum"/>
                            <xs:element type="xs:int" name="CustomerId"/>
                            <xs:element type="xs:int" name="ContractId"/>
                            <xs:element type="xs:string" name="PaymentDocument"/>
                        </xs:sequence>
                        <xs:attribute type="paymentType" name="target"/>
                        <xs:attribute type="directionType" name="flow"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="paymentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LOAN"/>
            <xs:enumeration value="DEPOSIT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="directionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="IN"/>
            <xs:enumeration value="OUT"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Grom33/PMN-ERP/xml/payment/payments.xml
<Payments xmlns="pmncloud"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="pmncloud payments.xsd">
    <Payment target="LOAN" flow="IN">
        <Id>1</Id>
        <Date>2018-10-12 </Date>
        <Sum>10000 </Sum>
        <CustomerId>1 </CustomerId>
        <ContractId>1</ContractId>
        <PaymentDocument>ПКО № 123 от 12.10.2018 </PaymentDocument>
    </Payment>
    <Payment target="LOAN" flow="IN">
        <Id>2</Id>
        <Date>2018-09-12 </Date>
        <Sum>9000 </Sum>
        <CustomerId>1 </CustomerId>
        <ContractId>1</ContractId>
        <PaymentDocument>ПКО № 80 от 12.09.2018 </PaymentDocument>
    </Payment>
    <Payment target="DEPOSIT" flow="IN">
        <Id>2</Id>
        <Date>2018-09-12 </Date>
        <Sum>9000 </Sum>
        <CustomerId>2</CustomerId>
        <ContractId>2</ContractId>
        <PaymentDocument>ПКО № 81 от 12.09.2018 </PaymentDocument>
    </Payment>
    <Payment target="DEPOSIT" flow="OUT">
        <Id>2</Id>
        <Date>2018-09-12 </Date>
        <Sum>9000 </Sum>
        <CustomerId>1</CustomerId>
        <ContractId>1</ContractId>
        <PaymentDocument>РКО № 40 от 12.09.2018 </PaymentDocument>
    </Payment>
</Payments>
