=== Grom33/PMN-ERP/xml/message/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="pmncloud"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="pmncloud"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Messages">
        <xs:complexType>
            <xs:all minOccurs="0">
                <xs:element name="Mails">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element name="Mail">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:element ref="Message"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="Addressee"/>
                                    <xs:attribute type="xs:string" name="Subject"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SMSes">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element name="SMS">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:element ref="Message"/>
                                        <xs:element type="xs:string" name="PhoneNumber"/>
                                        <xs:element type="xs:string" name="ResponseStatus"/>
                                        <xs:element type="xs:string" name="StatusTime"/>
                                        <xs:element type="xs:decimal" name="Cost"/>
                                        <xs:element type="xs:string" name="SMSId"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Message">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="UUID" nillable="true"/>
                <xs:element type="xs:string" name="Content">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:dateTime" name="DateTimeCreated"/>
                <xs:element type="xs:dateTime" name="DateTimeCompleted"/>
                <xs:element type="xs:dateTime" name="DateTimeToSend"/>
                <xs:element type="xs:int" name="UserId"/>
            </xs:sequence>
            <xs:attribute type="messageType" name="MsgType" use="required"/>
            <xs:attribute type="priorityType" name="Priority" use="required"/>
            <xs:attribute type="statusType" name="Status"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="messageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SYSTEM"/>
            <xs:enumeration value="USER"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priorityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LOW"/>
            <xs:enumeration value="MEDIUM"/>
            <xs:enumeration value="HIGH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="statusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CREATED"/>
            <xs:enumeration value="IN_PROCESS"/>
            <xs:enumeration value="SANDED"/>
            <xs:enumeration value="DELETED"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Grom33/PMN-ERP/xml/message/messages.xml
<Messages xmlns="pmncloud"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="pmncloud message.xsd">

    <Mails>
        <Mail Addressee="admin@google.ru" Subject="Hello friend">
            <Message MsgType="USER" Priority="MEDIUM" Status="CREATED">
                <UUID>b1a2841c-000a-437c-88b7-064ec1a628d4</UUID>
                <Content>fff</Content>
                <DateTimeCreated>2018-12-07T13:52:26</DateTimeCreated>
                <DateTimeCompleted>2018-12-07T13:52:26</DateTimeCompleted>
                <DateTimeToSend>2018-12-07T13:52:26</DateTimeToSend>
                <UserId>1</UserId>
            </Message>
        </Mail>
        <Mail Addressee="customer@google.ru" Subject="Order #123">
            <Message MsgType="USER" Priority="MEDIUM" Status="CREATED">
                <UUID>2a94a7ba-45ed-47a7-b5ad-82cb92c374d0</UUID>
                <Content>
                    Hello Dear customer !!!!
                </Content>
                <DateTimeCreated>2018-12-07T13:52:26</DateTimeCreated>
                <DateTimeCompleted>2018-12-07T13:52:26</DateTimeCompleted>
                <DateTimeToSend>2018-12-07T13:52:26</DateTimeToSend>
                <UserId>1</UserId>
            </Message>
        </Mail>
        <Mail Addressee="customer@google.ru" Subject="Order #123">
            <Message MsgType="USER" Priority="MEDIUM" Status="CREATED">
                <UUID>2a94a7ba-45ed-47a7-b5ad-82cb92c374d0</UUID>
                <Content>
                    Hello Dear customer !!!!
                </Content>
                <DateTimeCreated>2018-12-07T13:52:26</DateTimeCreated>
                <DateTimeCompleted>2018-12-07T13:52:26</DateTimeCompleted>
                <DateTimeToSend>2018-12-07T13:52:26</DateTimeToSend>
                <UserId>2</UserId>
            </Message>
        </Mail>
    </Mails>
    <SMSes>
        <SMS>
            <Message MsgType="USER" Priority="MEDIUM" Status="CREATED">
                <UUID>cffffea6-8831-420e-9001-5d2f6526ee19</UUID>
                <Content>fff</Content>
                <DateTimeCreated>2018-12-07T13:52:26</DateTimeCreated>
                <DateTimeCompleted>2018-12-07T13:52:26</DateTimeCompleted>
                <DateTimeToSend>2018-12-07T13:52:26</DateTimeToSend>
                <UserId>1</UserId>
            </Message>
            <PhoneNumber>+79062820232</PhoneNumber>
            <ResponseStatus>2018-12-07T13:52:26</ResponseStatus>
            <StatusTime>2018-12-07T13:52:26</StatusTime>
            <Cost>10.22</Cost>
            <SMSId>201851-1000002</SMSId>
        </SMS>
        <SMS>
            <Message MsgType="USER" Priority="MEDIUM" Status="">
                <UUID>cffffea6-8831-420e-9001-5d2f6526ee19</UUID>
                <Content>fff</Content>
                <DateTimeCreated>2018-12-07T13:52:26</DateTimeCreated>
                <DateTimeCompleted>2018-12-07T13:52:26</DateTimeCompleted>
                <DateTimeToSend>2018-12-07T13:52:26</DateTimeToSend>
                <UserId>1</UserId>
            </Message>
            <PhoneNumber>+79062820232</PhoneNumber>
            <ResponseStatus>2018-12-07T13:52:26</ResponseStatus>
            <StatusTime>2018-12-07T13:52:26</StatusTime>
            <Cost>10.22</Cost>
            <SMSId>201851-1000002</SMSId>
        </SMS>
    </SMSes>
</Messages>
