=== Grom33/PMN-ERP/xml/customer/customers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="pmncloud"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="pmncloud"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Customers">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Customer">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element type="xs:int" name="Id"/>
                            <xs:element type="xs:string" name="Name"/>
                            <xs:element type="xs:string" name="MiddleName"/>
                            <xs:element type="xs:string" name="Surname"/>
                            <xs:element type="xs:string" name="MaidName"/>
                            <xs:element type="gender" name="Gender"/>
                            <xs:element type="xs:string" name="BirthPlace"/>
                            <xs:element type="xs:date" name="BirthDay"/>
                            <xs:element type="xs:string" name="INN"/>
                            <xs:element type="xs:string" name="SNILS"/>
                            <xs:element type="xs:string" name="Email"/>
                            <xs:element name="Phones">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                        <xs:element ref="Phone"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Passports">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                        <xs:element ref="Passport"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Addresses">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                        <xs:element ref="Address"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="gender">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MALE"/>
            <xs:enumeration value="FEMALE"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MOBILE"/>
            <xs:enumeration value="WORK"/>
            <xs:enumeration value="HOME"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Phone">
        <xs:complexType>
            <xs:attribute type="phoneType" name="phoneType" use="required"/>
            <xs:attribute type="xs:string" name="number" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Passport">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="Serial"/>
                <xs:element type="xs:string" name="Number"/>
                <xs:element type="xs:date" name="Date"/>
                <xs:element type="xs:string" name="PassportOffice"/>
                <xs:element type="xs:string" name="OfficeCode"/>
                <xs:element type="xs:date" name="ExpirationDate"/>
            </xs:sequence>
            <xs:attribute type="xs:boolean" name="active"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Address">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="ZipCode"/>
                <xs:element type="xs:string" name="Region"/>
                <xs:element type="xs:string" name="City"/>
                <xs:element type="xs:string" name="Street"/>
                <xs:element type="xs:string" name="House"/>
                <xs:element type="xs:string" name="Flat"/>
            </xs:sequence>
            <xs:attribute type="addressType" name="addressType"/>
            <xs:attribute type="xs:boolean" name="active"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="addressType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RESIDENCE"/>
            <xs:enumeration value="REGISTRATION"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Grom33/PMN-ERP/xml/customer/customers.xml
<Customers xmlns="pmncloud"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="pmncloud customers.xsd">
    <Customer>
        <Id>1</Id>
        <Name>Иван</Name>
        <MiddleName>Иванович</MiddleName>
        <Surname>Иванов</Surname>
        <MaidName/>
        <Gender>MALE</Gender>
        <BirthPlace>Г. Санкт-Петербург</BirthPlace>
        <BirthDay>1982-11-23</BirthDay>
        <INN>123456789123</INN>
        <SNILS>123-123-123-99</SNILS>
        <Email>qwert@mail.ru</Email>
        <Phones>
            <Phone phoneType="MOBILE" number="9066782334"/>
            <Phone phoneType="HOME" number="8(812)123-22-34"/>
            <Phone phoneType="WORK" number="8(812)777-77-77"/>
        </Phones>
        <Passports>
            <Passport active="true">
                <Serial>1104</Serial>
                <Number>123456</Number>
                <Date>2005-02-03</Date>
                <PassportOffice> ОВД ПРИМОРСКОГО РАЙОНА</PassportOffice>
                <OfficeCode>292-002</OfficeCode>
                <ExpirationDate>2027-11-23</ExpirationDate>
            </Passport>
        </Passports>
        <Addresses>
            <Address addressType="RESIDENCE" active="true">
                <ZipCode>123456</ZipCode>
                <Region> Московская область</Region>
                <City>Москва</City>
                <Street>Прямая</Street>
                <House>123</House>
                <Flat>321</Flat>
            </Address>
            <Address addressType="REGISTRATION" active="true">
                <ZipCode>987654</ZipCode>
                <Region>Ленинградская область</Region>
                <City>Санкт-Петербург</City>
                <Street>Кривая</Street>
                <House>345</House>
                <Flat>32</Flat>
            </Address>
        </Addresses>
    </Customer>
    <Customer>
        <Id>2</Id>
        <Name>Сергей</Name>
        <MiddleName>Петрович</MiddleName>
        <Surname>Сидоров</Surname>
        <MaidName/>
        <Gender>MALE</Gender>
        <BirthPlace>Г. Витябск</BirthPlace>
        <BirthDay>1987-11-23</BirthDay>
        <INN>123466689123</INN>
        <SNILS>123-657-123-99</SNILS>
        <Email>qwert@mail.ru</Email>
        <Phones>
            <Phone phoneType="MOBILE" number="9052347787"/>
        </Phones>
        <Passports>
            <Passport active="true">
                <Serial>1222</Serial>
                <Number>128886</Number>
                <Date>2010-02-03</Date>
                <PassportOffice> ОВД ВОЛОГОДСКОГО РАЙОНА</PassportOffice>
                <OfficeCode>344-002</OfficeCode>
                <ExpirationDate>2032-11-23</ExpirationDate>
            </Passport>
        </Passports>
        <Addresses>
            <Address addressType="RESIDENCE" active="true">
                <ZipCode>123599</ZipCode>
                <Region> Московская область</Region>
                <City>Москва</City>
                <Street>Обычная</Street>
                <House>123</House>
                <Flat>321</Flat>
            </Address>
            <Address addressType="REGISTRATION" active="true">
                <ZipCode>987654</ZipCode>
                <Region>Вологодская область</Region>
                <City>Вологда</City>
                <Street>Красивая</Street>
                <House>5</House>
                <Flat>3</Flat>
            </Address>
        </Addresses>
    </Customer>
</Customers>
